### ISSUE TITLE
Add Support for seedXOR and One-Time-Pads

### ISSUE THREAD

**Issue by mchapiro1** [BitcoinQnA/seedtool#21]
SeedXOR and OTP are ways of turning a single seed into two new seeds in a way that provides perfect security if conditions are met. These methods have the advantage that they are easy to also compute by hand. SeedXOR enables the generation of valid seed words. A use can make a passphrase that fails to have enough entropy, whereas these methods do not allow entropy reduction. Additionally, on many devices, passphrase entry can be time consuming and less convenient.

SeedXOR overview here:
https://seedxor.com/

SeedXOR variant with 2 of 3 setup thread here:
https://twitter.com/nk1tz/status/1447328171334963201

Python implementation of OTP for bitcoin seeds here.
https://github.com/brndnmtthws/seed-otp

**Comment by SuperPhatArrow** [comment]
@mchapiro1 I have added this now and it will be in the next release (hopefully this week). It does not include Hamming backups (seedXOR 2 of 3) but it is an interesting challenge I would like to tackle in future. I will close this issue now but if you still want Hamming backups, please open a new issue specifically for that.

Thanks for your suggestions! I hope you continue to find the tool useful.
