### ISSUE TITLE
Make Raw Entropy as Mnemonic length available to support manual binary seed generation

### ISSUE THREAD

**Issue by curemici** [BitcoinQnA/seedtool#31]
Despite its presence in Ian Coleman's "Mnemonic Code Converter" the Menu item _"Use Raw Entropy (3 words per 32 bits)"_ is not part of the fantastic seedtool yet.
By choosing this option the user could determine the seed manually by generating binary entropy (11 bits per word) and calculate the words based on this as described in e.g. [Do you trust your seed, don't generate it yourself](https://estudiobitcoin.com/do-you-trust-your-seed-dont-generate-it-yourself/).

The seedtool could be used then for checking the own work and support the last word calculation.
Maybe this menu item needs some additional caption to avoid noob confusion.

**Comment by BitcoinQnA** [comment]
As discussed in DMs, this will be included in v1.0.6 release. Thank you for the suggestion.
