### ISSUE TITLE
[Feature request]: Display fingerprint and update it after applying passphrase

### ISSUE THREAD

**Issue by kdmukai** [BitcoinQnA/seedtool#33]
SeedSigner (and hopefully other wallet hardware/software) trains users to refer to their various keys by the fingerprint, especially when backing up their mnemonic and/or SeedQR.

So a user may have a backup that lists the target fingerprint but can no longer locate the passphrase that yielded that fingerprint.

But rather than doing the computation-heavy calculations that the current Passphrase Tester tool does, we'd just need the tool to display the resulting fingerprint after applying the passphrase. They can then quickly iterate through possible passphrases until they (hopefully) yield the target fingerprint they were looking for.

The fingerprint display will be generally useful (with or without a passphrase) as an addition to the info that's presented.

Also serves as yet another external validator to compare different BIP-39 implementations/HWWs to see if you get the same results.

**Comment by BitcoinQnA** [comment]
The tool already displays the fingerprint 
![Screenshot_20220528-161705](https://user-images.githubusercontent.com/64638670/170831577-30210091-bc7d-4b20-bb97-0456f55b872d.png)

I thought from what was mentioned on twitter that you wanted the fingerprint to be a field that the user could populate as a 'known info' instead of an address?

**Comment by kdmukai** [comment]
Ah, how did I miss that?! And I see it auto-updates as a passphrase is added or altered.

That's all we need then for the use case I'm describing: User knows the target fingerprint but is unsure of the password. They can just keep guessing and checking in real-time.
