### ISSUE TITLE
Feature Request: Testnet / Mainnet Selection for BIP47 Reusable Payment Codes

### ISSUE THREAD

**Issue by bro-rabbit** [BitcoinQnA/seedtool#39]
At Seed Tool v2.0.0 it is only possible to derive a Reusable Payment Code for a mainnet wallet.

Consider adding a toggle to the "_BIP47: Reusable Payment Codes_" section to switch between `mainnet` and `testnet`, as Reusable Payment Codes are derived differently for mainnet and testnet wallets. 

Consider setting the toggle to mainnet by default.

**Comment by SuperPhatArrow** [comment]
@bro-rabbit this has been added to main branch and will be in the next release. I will close this issue now but reopen it if there is more to add.
