### ISSUE TITLE
Optimisation Request: Add version number to top of page

### ISSUE THREAD

**Issue by bro-rabbit** [BitcoinQnA/seedtool#40]
Consider adding the Seed Tool version number to the top of the page (as below). This would be particularly helpful when working with the tool offline.

![image](https://user-images.githubusercontent.com/110024015/180977802-f41e1f79-928e-4d91-8097-c39bfb26c742.png)

**Comment by BitcoinQnA** [comment]
@SuperPhatArrow let me have a crack at this one.

**Comment by BitcoinQnA** [comment]
Implemented in e551d0aeb58568ed3a94eb697b7d290551bc4d22

Thanks @bro-rabbit
