### ISSUE TITLE
Add instructions for verifying release

### ISSUE THREAD

**Issue by KyleOfTheCorn** [BitcoinQnA/seedtool#47]
On the [releases](https://github.com/BitcoinQnA/seedtool/releases) page, there is a PGP signature block and a `signature.txt` file included, but no instructions on how to verify this. It's best practice to include these instructions in the project's main README file, or in each release, or both.

**Comment by BitcoinQnA** [comment]
Good suggestion, will get this added soon.

**Comment by BitcoinQnA** [comment]
Closed in https://github.com/BitcoinQnA/seedtool/commit/a5aeba7f196c2ec80afbe169eb2a7d94ec5b81d1
