### ISSUE TITLE
[BUG] Single address tool shouldn't treat private keys encoded in testnet WIF as invalid

### ISSUE THREAD

**Issue by GregTonoski** [BitcoinQnA/seedtool#48]
Expected result:
Accept WIF and calculate:
public key: 0255355ca83c973f1d97ce0e3843c85d78905af16b4dc531bc488e57212d230116
address: tb1p8wpt9v4frpf3tkn0srd97pksgsxc5hs52lafxwru9kgeephvs7rqlqt9zj

Actual result:
![image](https://user-images.githubusercontent.com/111286121/218334079-d547c4fd-b77b-4cd4-b56c-2e472ca9da99.png)

Steps to reproduce:
Input "cV628xvqToz45dwdPmTcJ9RgEVnWMwP8dpZBGzb9LfTk3sBHFNwc" into the field "Input a private key as WIF or Hex".

**Comment by SuperPhatArrow** [comment]
Should be fixed in the next release, thanks for the report.

![image](https://user-images.githubusercontent.com/38541071/218390394-7bafb314-ee48-495a-ac5f-62c05df4e913.png)

**Comment by GregTonoski** [comment]
Thanks for a fix.
