### ISSUE TITLE
TapRoot (P2TR) address in Single Address Tool section

### ISSUE THREAD

**Issue by GregTonoski** [BitcoinQnA/seedtool#51]
As a user, I want a TapRoot type of address to be show (alongside "legacy", "wrapped segwit" and "native segwit') so that I can learn all the of them in one place. (I suggest showing the raw TapRoot address generated from an "internal" a.k.a. "untweaked" public key: bc1pgrulsvazt3e9gqhzg2t9gy94hwvjm3875yegdq0s5azhrscsfcmqgk5wqt in the case shown in the image below).

![image](https://github.com/BitcoinQnA/seedtool/assets/111286121/27735dae-1fb9-431c-a57e-8a599deaa092)

**Comment by Jones098** [comment]
> As a user, I want a TapRoot type of address to be show (alongside "legacy", "wrapped segwit" and "native segwit') so that I can learn all the of them in one place. (I suggest showing the raw TapRoot address generated from an "internal" a.k.a. "untweaked" public key).
> 
> ![image](https://github.com/BitcoinQnA/seedtool/assets/111286121/27735dae-1fb9-431c-a57e-8a599deaa092)
> 

Thanks 🙏

**Comment by SuperPhatArrow** [comment]
Hi, 

Sorry it is not included, this definitely should have been part of this feature when it was released since we already had P2TR in the tool at that point.

I will add it ASAP and include it in the next update.

Thanks for bring this to my attention.

**Comment by SuperPhatArrow** [comment]
I believe this is now added:

![image](https://github.com/BitcoinQnA/seedtool/assets/38541071/3b5d025a-28df-4fda-8fa7-0a1a5c5caca5)

If everyone is happy we can merge into main to be included in the next release and close this issue.

**Comment by SuperPhatArrow** [comment]
@GregTonoski can you confirm that the above screenshot was what you requested here, please? I don't want to just close it if I misunderstood you in some way.

**Comment by GregTonoski** [comment]
I confirm that the screenshots includes what was requested. Thank you.
