### ISSUE TITLE
Feature request: BIP-85 Passwords

### ISSUE THREAD

**Issue by MeisterEdersCarpentry** [BitcoinQnA/seedtool#55]
Add the BIP855 password to the "BIP85 Application dropdown".
The [coldcard](https://coldcard.com/docs/bip85-passwords) mk4 is able to produce a 21 character password based on the BIP-85 spec. To my understanding it derived from PWD BASE64 as explained in the [BIP](https://github.com/scgbckbone/bips/blob/passwords/bip-0085.mediawiki#pwd-base64).

Beside the offline password manager possibilities, this is a great way of deriving multiple passphrases based on one master seed.

**Comment by BitcoinQnA** [comment]
Perhaps we could drum up a bounty for @SuperPhatArrow to implement this. What do you think @MeisterEdersCarpentry ?

**Comment by jonjonez** [comment]
Is this in the works? That would be a huge milestone!

**Comment by BitcoinQnA** [comment]
Still looking to drum up a bounty for @SuperPhatArrow to them to spend some time on this.

**Comment by BitcoinQnA** [comment]
Closed and will form part of an upcoming release.
