### ISSUE TITLE
Entering own mnemonic phrase filling behavior

### ISSUE THREAD

**Issue by rapidlab309** [BitcoinQnA/seedtool#56]
On pasting a mnemonic phrase into SeedTool, only the first slot is being filled, and with all of the words.
A better behavior would be that each word will be placed into the right slot, based on space or known given word.

![image](https://github.com/BitcoinQnA/seedtool/assets/96245140/beff2fd4-76b8-4e56-b71c-4de2f847e73e)

**Comment by SuperPhatArrow** [comment]
Agree, this is much better UX. I'll assign it to me next time I can work on this unless someone does first.
