### ISSUE TITLE
Word Indexes starting with "0"

### ISSUE THREAD

**Issue by edbfraga** [BitcoinQnA/seedtool#60]
When you enter in Entropy Section and then find "Word Indexes" you will get an incorrect correspondence. 

Abandon = Word index "0" - the correct is "1"
Ability = Word index "1" - the correct is "2"
Able = Word index "2" - the correct is "3"

**Comment by BitcoinQnA** [comment]
This in incorrect. Abandon is the first in the list, which starts at 0.
