### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by satscoffee** [BitcoinQnA/seedtool#62]
https://github.com/BitcoinQnA/seedtool/blob/be23715d5681f65b7515cb27dbdee6b9da45d55a/src/www/js/info.js#L332

Withness should be Witness

**Comment by BitcoinQnA** [comment]
This would be a great first issue to get you on the contributors list. Would you like to have a go at changing the text and making a Pull Request @satscoffee ?

**Comment by satscoffee** [comment]
I'll take a shot. Wish me luck.
