### ISSUE TITLE
Public key not available

### ISSUE THREAD

**Issue by ericvt** [BitcoinQnA/seedtool#63]
the public key service doesn't seem to be up @ https://bitcoiner.guide/public.key

**Comment by SuperPhatArrow** [comment]
That is not part of this repo.

@BitcoinQnA do you know what this is about?

**Comment by PabiGamito** [comment]
Same issue. Getting 404 when trying to load the key.

**Comment by BitcoinQnA** [comment]
My PGP key can be found at https://bitcoiner.guide/pgp/
